animal = "   waIu fEliz   "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("E"))
print(animal.replace("wa", "Wa"))
print("waI" in animal)
print("waI" not  in animal)
